In [65]:
# https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/keras/rnn.ipynb#scrollTo=jfOdaQLhXLDR
from __future__ import absolute_import, division, print_function, unicode_literals
import collections
import matplotlib.pyplot as plt
import numpy as np

import tensorflow as tf
from tensorflow.keras import layers

#built-in RNN : tf.kras.layers.SimpleRNN, tf.keras.layers.GRU, tf.keras.layers.LSTM

model = tf.keras.Sequential()
model.add(layers.Embedding(input_dim=4422100, output_dim=10))

#Add a LSTM layer with 128 internal units
model.add(layers.LSTM(128))

#Add a Dense layer with 10 units and softmax activation
model.add(layers.Dense(10, activation='softmax'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, None, 10)          44221000  
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               71168     
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1290      
Total params: 44,293,458
Trainable params: 44,293,458
Non-trainable params: 0
_________________________________________________________________


In [11]:
model = tf.keras.Sequential()
model.add(layers.Embedding(input_dim=1000, output_dim=64))

model.add(layers.GRU(256, return_sequences=True))
model.add(layers.SimpleRNN(128))
model.add(layers.Dense(10, activation='softmax'))

model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, None, 64)          64000     
_________________________________________________________________
gru_2 (GRU)                  (None, None, 256)         247296    
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (None, 128)               49280     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1290      
Total params: 361,866
Trainable params: 361,866
Non-trainable params: 0
_________________________________________________________________


In [57]:
#1. 데이터 준비
import os
import sys

def search(dirname):
    filenames = os.listdir(dirname) #리스트
    full_filenames
    for filename in filenames:
        full_filenames = os.path.join(dirname, filename) #단어 단위
        
        '''for full_filename in full_filenames:
            full_textfilenames = os.path.join(dirname, full_filname) #텍스트 단위
            print(full_textfilenames)
        '''
        #with open(full_filename,"r")
          
        
        
search('/Users/anna/SLR/train_data/')
print(full_filenames)

NameError: name 'full_filenames' is not defined

In [24]:
#1. 데이터 준비
import numpy as np
import os

#파일 읽기
predict = []
with open("/Users/anna/SLR/train_data/Argentina/024_001_001.txt", 'r') as data:
    numbers = [[i for i in line.split(' ')] for line in data.readlines()]
    numbers.append("arhentia")
predict.append(numbers)
#print(predict)

['Bright', '.DS_Store', 'Light-blue', 'Bitter', 'Milk', 'Argentina', 'Birthday', 'Enemy', 'Call', 'Deaf', 'Colors', 'Opaque', 'Chewing-gum', 'Find', 'Yellow', 'Name', 'None', 'Buy', 'Country', 'Candy']


In [2]:
from __future__ import absolute_import, division, print_function, unicode_literals
import pickle
import numpy as np


X = []
Y = []

with open("/Users/anna/SLR/data.pkl", 'rb') as fin:
    frames = pickle.load(fin)
    for i, frame in enumerate(frames):
        features = frame[0]
        word = frame[1]
        
        X.append(np.array(features))
        Y.append(word)
X = np.array(X)
Y = np.array(Y)
np.shape(X)


(x_train, y_train) = X, Y
        

In [ ]:
#3분 케라스 책에 있는 RNN
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import model_selection
from keras import models, layers

from kerasapp import skeras


def main():
    machine = Machine()
    machine.run(epochs=400)
    
class Machine():
    def __init__(self):
        self.data = Dataset()
        shape = self.data.X.shape[1:]
        self.model = rnn_model(shape)
        
        def run(self, epochs = 400):
            d = self.data
            X_train, X_test = d.X_train, d.X_test
            y_train, y_test = d.y_train, d.y_test
            X, y = d.X, d.y
            m = self.model
            h = m.fit(X_train, y_train, epochs=epochs, validation_data =[X_test, y_test], verbose=0)
            
            skeras.plot_loss(h)
            plt.title("History of training")
            plt.show()
            
            yp = m.predict(X_test)
            print('Loss:', m.evalutate(X_test, y_test))
            plt.plot(yyp, label='Original')
            plt.plot(y_test, label='Prediction')
            
            plt.legend(loc=0)
            plt.title('Validation Results')
            plt.show()
            
            yp = m.predict(X_test).reshape(-1)
            print('Loss:', m.evaluate(X_test, y_test))
            print(yp.shape, y_test.shape)
            
            df = pd.DataFrame()
            df['Sample'] = list(range(len(y_test))) * 2
            df['Normalized #Passengers'] = np.concatenate([y_test, yp], axis=0)
            df['Type'] = ['Original'] * len(y_test) + ['Prediction'] + len(yp)
            
            plt.figure(figsize=(7,5))
            sns.barplot(x="Sample", y="Normalized #Passengers", hue="Type", data=df)
            plt.ylabel("Normalized #Passengers")
            plt.show()
            
            yp = m.predict(X)
            
            plt.plot(yp, label='Original')
            plt.plot(y, label='Prediction')
            plt.legend(loc=0)
            plt.title('All Results')
            plt.show()
            
            
        def rnn_model(shape):
            m_x = layers.Inputs(shape=shape)
            m_h = layers.LSTM(10)(m_x)
            m_y = layers.Dense(1)(m_h)
            m = models.Model(m_x, m_y)
            
            m.compile('adam', 'mean_squared_error')
            
            m.summary()
            
            return m
        
        
        def Dataset:
            def __init__(self, frame='international-airline-passengers.csv' D=12)
            data_on = load_data(fname=fname)
            X, y = get_Xy(data_dn, D=D)
            X_train, X_test, y_train, y_test = model.selection.train_test_split(X, y, test_size=0.2, random_state=42)
            
        
        def load_data(fname='internatinal-airline')

In [24]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
X = []
Y = []

with open("/Users/anna/SLR/data.pkl", 'rb') as fin:
    frames = pickle.load(fin)
    for i, frame in enumerate(frames):
        features = frame[0]
        word = frame[1].lower()
        
        X.append(np.array(features))
        Y.append(word)
X = np.array(X)
Y = np.array(Y)
t = Tokenizer()
t.fit_on_texts(Y)
print(t.word_index)
#Y = to_categorical(Y,len(t.word_index))
encoded=t.texts_to_sequences(Y)
#print(encoded)
one_hot=to_categorical(encoded)
print(one_hot)


#Y = t.texts_to_sequences(Y)[0]
#print(Y)

{'bitter': 1, 'milk': 2, 'argentina': 3, 'deaf': 4, 'chewinggum': 5, 'name': 6, 'none': 7, 'buy': 8, 'country': 9, 'lightblue': 10}
[[0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]]


In [26]:
"""
LSTM example for Keras
======================
Object oriented style revision of the original code in Keras example
- https://github.com/fchollet/keras/blob/master/examples/imdb_lstm.py   
"""

from __future__ import absolute_import, division, print_function, unicode_literals
from keras.preprocessing import sequence
from keras.datasets import imdb
from keras import layers, models
import pickle
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical


class Data:
    def __init__(self):
        
        X = []
        Y = []
        
        with open("/Users/anna/SLR/data.pkl", 'rb') as fin:
            frames = pickle.load(fin)
            for i, frame in enumerate(frames):
                features = frame[0]
                word = frame[1]
            
                X.append(np.array(features))
                Y.append(word)
        X = np.array(X)
        Y = np.array(Y)

        t = Tokenizer()
        t.fit_on_texts(Y)
        #print(t.word_index)
        #Y = to_categorical(Y,len(t.word_index))
        encoded=t.texts_to_sequences(Y)
        #print(encoded)
        one_hot=to_categorical(encoded)
        #print(one_hot)

       
        (x_train, y_train) = X, one_hot
        
        self.x_train, self.y_train = x_train, y_train
        self.x_test, self.y_test = x_train, y_train
        
        
class RNN_LSTM(models.Model):
    def __init__(self):
        x = layers.Input((8736,))
        h = layers.Embedding(8736, 128)(x)
        h = layers.LSTM(128, dropout=0.2, recurrent_dropout=0.2)(h)
        y = layers.Dense(11, activation='softmax')(h)
        super().__init__(x, y)

        # try using different optimizers and different optimizer configs
        self.compile(loss='binary_crossentropy',
                     optimizer='adam', metrics=['accuracy'])


class Machine:
    def __init__(self):
        self.data = Data()
        self.model = RNN_LSTM()

    def run(self, epochs=3, batch_size=32):
        data = self.data
        model = self.model
        print('Training stage')
        print('==============')
        model.fit(data.x_train, data.y_train,
                  batch_size=batch_size,
                  epochs=epochs,
                  validation_data=(data.x_test, data.y_test))

        score, acc = model.evaluate(data.x_test, data.y_test,
                                    batch_size=batch_size)
        print('Test performance: accuracy={0}, loss={1}'.format(acc, score))


def main():
    m = Machine()
    m.run()


if __name__ == '__main__':
    main()

Training stage


//anaconda3/envs/SLR/lib/python3.7/site-packages/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 500 samples, validate on 500 samples
Epoch 1/3
500/500 [==============================] - 387s 774ms/step - loss: 0.3023 - accuracy: 0.9091 - val_loss: 0.2980 - val_accuracy: 0.9091
Epoch 2/3
500/500 [==============================] - 380s 760ms/step - loss: 0.2988 - accuracy: 0.9091 - val_loss: 0.2963 - val_accuracy: 0.9091
Epoch 3/3
500/500 [==============================] - 49s 97ms/step
Test performance: accuracy=0.9090909361839294, loss=0.29645157051086424


In [ ]:
"""
LSTM example for Keras
======================
Object oriented style revision of the original code in Keras example
- https://github.com/fchollet/keras/blob/master/examples/imdb_lstm.py   
"""

from __future__ import absolute_import, division, print_function, unicode_literals
from keras.preprocessing import sequence
from keras.datasets import imdb
from keras import layers, models
import pickle
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical


class Data:
    def __init__(self,pklname):
        
        X = []
        Y = []
        maxlength=0
        with open(pklname, 'rb') as fin:
            frames = pickle.load(fin)
            for i, frame in enumerate(frames):
                features = frame[0]
                maxlength=len(features)
                word = frame[1]
            
                X.append(np.array(features))
                Y.append(word)
        X = np.array(X)
        Y = np.array(Y)

        t = Tokenizer()
        t.fit_on_texts(Y)
        #print(t.word_index)
        #Y = to_categorical(Y,len(t.word_index))
        encoded=t.texts_to_sequences(Y)
        #print(encoded)
        one_hot=to_categorical(encoded)
        #print(one_hot)

       
        (x_train, y_train) = X, one_hot
        
        self.x_train, self.y_train = x_train, y_train
        self.x_test, self.y_test = x_train, y_train
        self.length=maxlength
        
class RNN_LSTM(models.Model):
    def __init__(self,maxlen):
        x = layers.Input((maxlen,))
        h = layers.Embedding(maxlen, 128)(x)
        h = layers.LSTM(128, dropout=0.2, recurrent_dropout=0.2)(h)
        y = layers.Dense(9, activation='softmax')(h)
        super().__init__(x, y)

        # try using different optimizers and different optimizer configs
        self.compile(loss='binary_crossentropy',
                     optimizer='adam', metrics=['accuracy'])


class Machine:
    def __init__(self,pklname):
        self.data = Data(pklname)
        self.model = RNN_LSTM(self.data.length)

    def run(self, epochs=3, batch_size=32):
        data = self.data
        model = self.model
        print('Training stage')
        print('==============')
        model.fit(data.x_train, data.y_train,
                  batch_size=batch_size,
                  epochs=epochs,
                  validation_data=(data.x_test, data.y_test))

        score, acc = model.evaluate(data.x_test, data.y_test,
                                    batch_size=batch_size)
        print('Test performance: accuracy={0}, loss={1}'.format(acc, score))


def main(pklname):
    m = Machine(pklname)
    m.run()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='run Model')
    parser.add_argument("--pkl_data_path",help=" ")
    args=parser.parse_args()
    pkl_data_path=args.pkl_data_path
    main(pkl_data_path)

Training stage


//anaconda3/envs/SLR/lib/python3.7/site-packages/tensorflow_core/python/framework/indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Train on 411 samples, validate on 411 samples
Epoch 1/3
411/411 [==============================] - 84s 205ms/step - loss: 0.3455 - accuracy: 0.8889 - val_loss: 0.3392 - val_accuracy: 0.8889
Epoch 2/3
384/411 [===========================>..] - ETA: 4s - loss: 0.3393 - accuracy: 0.8889 

In [67]:
from __future__ import absolute_import, division, print_function, unicode_literals
import collections
import matplotlib.pyplot as plt
import numpy as np

import tensorflow as tf
from tensorflow.keras import layers

#built-in RNN : tf.kras.layers.SimpleRNN, tf.keras.layers.GRU, tf.keras.layers.LSTM

model = tf.keras.Sequential()
model.add(layers.Embedding(input_dim=8736, output_dim=10)) #최대길이 8736

#Add a LSTM layer with 128 internal units
model.add(layers.LSTM(128))

#Add a Dense layer with 10 units and softmax activation
model.add(layers.Dense(10, activation='softmax'))
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_6 (Embedding)      (None, None, 10)          42840     
_________________________________________________________________
lstm_3 (LSTM)                (None, 128)               71168     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1290      
Total params: 115,298
Trainable params: 115,298
Non-trainable params: 0
_________________________________________________________________


In [70]:
list = [0,1,2]
list[0]

0